// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2xM9e5xAj4XvwNm4GN-oYOfEEmCYIfI4',
    appId: '1:684410585726:web:b82a90bbdd3bbe58240e2f',
    messagingSenderId: '684410585726',
    projectId: 'social-19efe',
    authDomain: 'social-19efe.firebaseapp.com',
    storageBucket: 'social-19efe.appspot.com',
    measurementId: 'G-WG8WBD3VSE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAD5QeAsjufP1cNbeB2sVmQSG3Kx1phfos',
    appId: '1:684410585726:android:abe20fd3ae655ab6240e2f',
    messagingSenderId: '684410585726',
    projectId: 'social-19efe',
    storageBucket: 'social-19efe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrFtPRaq42LsRV86IEK6k4QWnIwuFskac',
    appId: '1:684410585726:ios:f0ea4dcd3aa1a058240e2f',
    messagingSenderId: '684410585726',
    projectId: 'social-19efe',
    storageBucket: 'social-19efe.appspot.com',
    iosBundleId: 'com.example.social',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrFtPRaq42LsRV86IEK6k4QWnIwuFskac',
    appId: '1:684410585726:ios:f0ea4dcd3aa1a058240e2f',
    messagingSenderId: '684410585726',
    projectId: 'social-19efe',
    storageBucket: 'social-19efe.appspot.com',
    iosBundleId: 'com.example.social',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2xM9e5xAj4XvwNm4GN-oYOfEEmCYIfI4',
    appId: '1:684410585726:web:276ee39255fa5adf240e2f',
    messagingSenderId: '684410585726',
    projectId: 'social-19efe',
    authDomain: 'social-19efe.firebaseapp.com',
    storageBucket: 'social-19efe.appspot.com',
    measurementId: 'G-941K64RWFV',
  );
}
